name: budget_tracker_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  sqflite: ^2.4.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  uses-material-design: true

  assets:
    - assets/images/category/
    - assets/bg/